# Generated by Django 3.2.8 on 2021-11-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('cart_id', models.CharField(blank=True, max_length=100)),
                ('total_cart_items', models.PositiveBigIntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated_at', models.DateField(auto_now_add=True, verbose_name='Last Updated')),
                ('restaurant', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer+', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('SSLCommerz', 'SSLCommerz')], default='COD', max_length=20, verbose_name='Payment Method')),
                ('is_paid', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_time', models.DateField(auto_now_add=True, verbose_name='Delivery Time')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('order_num', models.CharField(max_length=100, verbose_name='Order Number')),
                ('restaurant', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated_at', models.DateField(auto_now_add=True, verbose_name='Last Updated')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartOrder.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer+', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem_id', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated_at', models.DateField(auto_now_add=True, verbose_name='Last Updated')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartOrder.cart')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food+', to='food.food', verbose_name='Food')),
            ],
            options={
                'verbose_name_plural': 'Shopping Cart Items',
            },
        ),
    ]
