# Generated by Django 3.2.8 on 2021-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartOrder', '0002_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received by Restaurant', 'Order Received by Restaurant'), ('Baking', 'Baking'), ('Baked', 'Baked'), ('Out for Delivery', 'Out for Delivery'), ('Order Received by Customer', 'Order Received by Customer')], default='Order Received by Restaurant', max_length=100),
        ),
    ]
